services:
  transcendence:
    image: transcendence
    build:
      context: .
      dockerfile: transcendence/Dockerfile

  transcendence.webapi:
    image: transcendence.webapi
    build:
      context: .
      dockerfile: transcendence.WebAPI/Dockerfile

  transcendence.service:
    image: transcendence.service
    build:
      context: .
      dockerfile: transcendence.Service/Dockerfile

  transcendence.webadminportal:
    image: transcendence.webadminportal
    build:
      context: .
      dockerfile: transcendence.WebAdminPortal/Dockerfile
