services:
  transcendence.webapi:
    image: transcendence.webapi
    build:
      context: .
      dockerfile: Transcendence.WebAPI/Dockerfile

  transcendence.service:
    image: transcendence.service
    build:
      context: .
      dockerfile: Transcendence.Service/Dockerfile

  transcendence.webadminportal:
    image: transcendence.webadminportal
    build:
      context: .
      dockerfile: Transcendence.WebAdminPortal/Dockerfile
